### ISSUE TITLE
中文字体混乱

### ISSUE THREAD

**Issue by love98ooo** [NJUPT-SAST-Cpp/SAST-Evento-Desktop#100]
部分中文会出现多种字体同时渲染
![image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/77888749/a5f24824-1f1b-41a0-a248-09c2587c1f75)

**Comment by love98ooo** [comment]
Windows Display Language: English(Unites States) 环境下显示异常；中文（中华人民共和国）环境下显示正常

**Comment by ArcticLampyrid** [comment]
似乎是默认字体的问题

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Serein207** [comment]
系统语言是英语的情况下会出现中文字体无法统一的问题，正在排查

**Comment by MaxtuneLee** [comment]
同样出现该问题

**Comment by Serein207** [comment]
正在考虑将字体文件随资源文件一起打包

**Comment by Serein207** [comment]
fixed
