### ISSUE TITLE
English Language 未完全适配

### ISSUE THREAD

**Issue by love98ooo** [NJUPT-SAST-Cpp/SAST-Evento-Desktop#101]
![image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/77888749/1e29f9bc-4500-49c2-8b58-06d0f305772c)
![image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/77888749/d175fb7e-dca7-4eca-b9ae-1444de489772)
![image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/77888749/48267a04-016c-4022-b367-924c64ea5879)
![image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/77888749/8e4a850b-7ebe-4bef-bbe6-7faf379ad108)
目前找到如上几处

**Comment by ArcticLampyrid** [comment]
感谢反馈，内测版的多语言功能并未完成开发，还请谅解

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Cai Liao ***@***.***>
Sent: Saturday, September 30, 2023 5:01:50 PM
To: NJUPT-SAST-Cpp/SAST-Evento-Desktop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NJUPT-SAST-Cpp/SAST-Evento-Desktop] English Language 未完全适配 (Issue #101)


[image]<https://user-images.githubusercontent.com/77888749/271764109-1e29f9bc-4500-49c2-8b58-06d0f305772c.png>
[image]<https://user-images.githubusercontent.com/77888749/271764140-d175fb7e-dca7-4eca-b9ae-1444de489772.png>
[image]<https://user-images.githubusercontent.com/77888749/271764166-48267a04-016c-4022-b367-924c64ea5879.png>
[image]<https://user-images.githubusercontent.com/77888749/271764302-8e4a850b-7ebe-4bef-bbe6-7faf379ad108.png>
目前找到如上几处

―

**Comment by Serein207** [comment]
系统语言是英语的情况下会出现中文字体无法统一的问题，正在排查
