### ISSUE TITLE
Calendar 弹出窗口无法调整大小，icon重叠

### ISSUE THREAD

**Issue by MaxtuneLee** [NJUPT-SAST-Cpp/SAST-Evento-Desktop#106]
![image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/60775796/2d37e9b3-5f68-4fc9-8252-b65b5c0b4af2)
如上图所示，此窗口无法调整大小，且右上角icon重叠

**Comment by Serein207** [comment]
icon重叠已修复
窗口无法调节大小是故意这样设计的
