### ISSUE TITLE
退出程序失败，程序失去响应

### ISSUE THREAD

**Issue by MaxtuneLee** [NJUPT-SAST-Cpp/SAST-Evento-Desktop#111]
平台：Macbook Pro arm64
退出程序时候有个弹窗，点击退出后程序无法退出，并且卡死失去响应
<img width="357" alt="image" src="https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/60775796/daec72b6-ec14-4b11-b9c1-cbe5f0956772">

**Comment by Serein207** [comment]
之前的版本就有这个问题吗，还是1004才出现的问题？

**Comment by MaxtuneLee** [comment]
1004才有的问题

**Comment by ArcticLampyrid** [comment]
是否有log？

**Comment by Serein207** [comment]
新版本并没有对有关程序退出的逻辑进行改动，无法定位错误
