### ISSUE TITLE
Controller: Login

### ISSUE THREAD

**Issue by Serein207** [NJUPT-SAST-Cpp/SAST-Evento-Desktop#16]
- 身份验证
- 获取权限表
- 处理权限表

**Comment by ArcticLampyrid** [comment]
![image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/9017609/f71a69cd-9513-44b7-a406-e298ad812bdc)

wait for sastlink team

**Comment by Serein207** [comment]
咕咕

**Comment by ArcticLampyrid** [comment]
## Related

组件：Qt WebEngine

类：
- QWebEngineUrlScheme
- QWebEngineView

**Comment by ArcticLampyrid** [comment]
## Design
- Login 载入一个 QWebEngineView
- Callback （auth 的 redirect）到一个自定义 scheme
- 通过 QWebEngineUrlScheme 注册自定义 scheme 响应 SASTLink 返回的 code

## Note
- 根据协调，SASTLink 中的 redirect uri 具有黑白名单机制，需要后端方面协助将相关自定义 scheme 加入白名单
- client id 暂定为 `2881931d-be37-4075-924e-3a2d5685245f` （测试后端所用 UUID），正式版本可能更换
- code_challenge 参数待协调，Evento方文档未描述 PKCE 流程有关信息

**Comment by ArcticLampyrid** [comment]
另需讨论，使用 SASTLink 后，如何同时做测试版（localdata impl）的登陆界面比较好

**Comment by Serein207** [comment]
登录界面需要重写，目前规划是两个button，分别是link登录和微信登录，微信登录先不做

**Comment by ArcticLampyrid** [comment]
跳转到Link后，Link界面是有微信登录、飞书登录等按钮的（虽然Link那边目前还没完成）
似乎没有必要再加一个独立的微信登录按钮
