### ISSUE TITLE
Controller: UserManagement

### ISSUE THREAD

**Issue by Serein207** [NJUPT-SAST-Cpp/SAST-Evento-Desktop#24]
![Image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/118594118/e58dcd3c-8821-4144-8249-3282d498c135)
![Image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/118594118/4ae9490e-f72c-437a-b4e2-da8a17db2f36)

**Comment by FormerOR** [comment]
这个二级页面是不是要新建一个QML的文件

**Comment by Serein207** [comment]
> 这个二级页面是不是要新建一个QML的文件

bingo

**Comment by FormerOR** [comment]
这里的权限1234是用来做什么的，一个listview展示该用户拥有的所有权限吗?
![image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/110514151/4e515f43-207d-4aeb-9773-1aa477d9b774)

**Comment by Serein207** [comment]
> 这里的权限1234是用来做什么的，一个listview展示该用户拥有的所有权限吗? ![image](https://user-images.githubusercontent.com/110514151/263459132-4e515f43-207d-4aeb-9773-1aa477d9b774.png)

左边树形选择框选择完成后点击载入，右边以list形式展示所有选择的权限

在编辑权限的情况下，需要加载用户当前已有的权限在右边展示

**Comment by Serein207** [comment]
树状列表改为一级列表

**Comment by FormerOR** [comment]
> 树状列表改为一级列表

一级列表?

**Comment by FormerOR** [comment]
就是说直接将所有权限列出来，不用展开才能看到权限吗

**Comment by Serein207** [comment]
一级列表参考活动编辑界面的部门列表
左边展示所有权限，右边展示所有用户已有的权限

**Comment by Serein207** [comment]
可以考虑设置一个flag，子节点的 `checked` 和这个flag状态绑定。父节点的checkbox被选定后修改flag值
