### ISSUE TITLE
Controller: SildeManagement

### ISSUE THREAD

**Issue by Serein207** [NJUPT-SAST-Cpp/SAST-Evento-Desktop#25]
![Image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/118594118/53207d2d-6fcc-4663-aff2-dc1cff7c2532)
![Image](https://github.com/NJUPT-SAST-Cpp/SAST-Evento-Desktop/assets/118594118/511db61c-0f83-4585-9ded-171bd8670b4f)

**Comment by ssttyy123** [comment]
需要编写helper文件以供从一级页面向二级页面跳转提供数据
