### ISSUE TITLE
UI线程阻塞

### ISSUE THREAD

**Issue by Serein207** [NJUPT-SAST-Cpp/SAST-Evento-Desktop#63]
- 在 `src/controller` 下新增 xxModule： 新开 `QThread` 调用 `repository` 并使用Convertor转换（即原 `src/controller/ui` Controller的 `Q_INVOKABLE` 函数体），注意加锁（`static` 互斥量）
- xx根据entity命名，对于同一个model或者helper的处理放在一个Module中
- Module在处理请求完成后发送成功或失败信号（或是状态量），Controller接收信号，connect函数写在Controller的ctor中
- `Q_INVOKABLE` 函数改为简单地调用xxModule的成员函数，不执行任何业务逻辑
- Controller接收到Module信号后，槽函数将信号继续转发给qml
- 如果原 `Q_INVOKABLE` 函数返回一个值，改为通过Module和Controller使用信号槽传递这个值

**Comment by ArcticLampyrid** [comment]
QFuture 应该足够作为通知机制，可能不需要映入额外的 Module 机制

**Comment by Serein207** [comment]
> QFuture 应该足够作为通知机制，可能不需要映入额外的 Module 机制

你那能找一个Q_INVOKABLE函数重写演示一下一整套异步发送请求的逻辑吗

**Comment by Serein207** [comment]
所有非空返回的`Q_INVOKABLE`函数改为使用信号槽传递数据（注意使用值语义）
@feipiao594 @ssttyy123 @FormerOR 
修改各自负责的UI，注意把pr关联到issue

**Comment by ArcticLampyrid** [comment]
目前不是已经使用信号槽传递数据并用过 successEvent 和 failedEvent 返回给 qml 了吗？

**Comment by Serein207** [comment]
> 目前不是已经使用信号槽传递数据并用过 successEvent 和 failedEvent 返回给 qml 了吗？

这只是成功或失败信号。如果Q_INVOKABLE返回一个值，那一定会阻塞主线程。这是没有helper类的一种折中方案
